In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [5]:
df = pd.read_csv('home_price.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [12]:
median_1 = df.bedrooms.median()
df.bedrooms = df.bedrooms.fillna(median_1)
print(df)

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000


In [21]:
model = linear_model.LinearRegression()
model.fit(df[['area','bedrooms','age']], df.price)
model.predict([[3000,3,40]])

/Users/megha_agrawal/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [18]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [19]:
model.intercept_

221323.00186540396

In [20]:
y = 3000*112.06244194 + 3* 23388.88007794 + 40 * (-3231.71790863) + 221323.00186540396
print(y)

498408.251574024


### 2nd csv file 



In [57]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [24]:
!pip install word2number

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5566 sha256=cb72c648ae1a21ce4c7570e26432d55b2fa4e3f553ddbe2fa4303c9cf13bf432
  Stored in directory: /Users/megha_agrawal/Library/Caches/pip/wheels/21/1d/b2/768b65901d249c6eb2a8d9c30392506555a4e94055ba4e0aa0
Successfully built word2number
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the n

In [58]:
from word2number import w2n
expe = []
for x in range(df.experience.size):
    if str(df.experience[x]) != "nan":
        df.experience[x] = (w2n.word_to_num(str(df.experience[x])))
expe = df.experience.median()
expe

/var/folders/8m/1dnpz6nj08b837gqqm667sr00000gn/T/ipykernel_75265/1856387719.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.experience[x] = (w2n.word_to_num(str(df.experience[x])))


6.0

In [59]:
df.experience = df.experience.fillna(expe)
score = df['test_score(out of 10)'].median()
print(score)

8.0


In [60]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [61]:
model = linear_model.LinearRegression()
model.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']], df['salary($)'])
model.coef_


array([2813.00813008, 1333.33333333, 2926.82926829])

In [62]:
model.intercept_

11869.91869918695

In [65]:
model.predict([[12,10,10]])

/Users/megha_agrawal/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88227.64227642])